"""add audio chunk model

Revision ID: 471a89112166
Revises: 5897027ba978
Create Date: 2026-06-12 21:26:14.874505
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471a89112166'
down_revision: Union[str, None] = '5897027ba978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_chunks',
    sa.Column('bot_session_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('minio_key', sa.String(length=500), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=20), server_default='webm', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_session_id'], ['bot_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audio_chunks_meeting', 'audio_chunks', ['meeting_id'], unique=False)
    op.create_index('idx_audio_chunks_session_order', 'audio_chunks', ['bot_session_id', 'chunk_index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audio_chunks_session_order', table_name='audio_chunks')
    op.drop_index('idx_audio_chunks_meeting', table_name='audio_chunks')
    op.drop_table('audio_chunks')
    # ### end Alembic commands ###
