"""initial

Revision ID: 5897027ba978
Revises: 
Create Date: 2026-06-12 15:57:07.366135
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5897027ba978'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='chk_org_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=190), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='INVITED', nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('invite_token', sa.String(length=100), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('ADMIN', 'HOST', 'USER')", name='chk_user_role'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INVITED', 'DISABLED')", name='chk_user_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_users_org_role', 'users', ['organization_id', 'role'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_lookup', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_table('projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_org_name', 'projects', ['organization_id', 'name'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('parent_token', sa.String(length=255), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_refresh_tokens_lookup', 'refresh_tokens', ['token'], unique=False)
    op.create_table('meetings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('host_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=30), server_default='GOOGLE_MEET', nullable=False),
    sa.Column('meeting_url', sa.Text(), nullable=False),
    sa.Column('scheduled_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='SCHEDULED', nullable=False),
    sa.Column('language_config', postgresql.JSONB(astext_type=sa.Text()), server_default='["en", "hi"]', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('SCHEDULED', 'BOT_STARTING', 'WAITING_FOR_ADMISSION', 'IN_PROGRESS', 'PROCESSING_TRANSCRIPT', 'GENERATING_REPORT', 'COMPLETED', 'FAILED', 'CANCELLED')", name='chk_meeting_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meetings_idempotency', 'meetings', ['idempotency_key'], unique=True, postgresql_where='idempotency_key IS NOT NULL')
    op.create_index('idx_meetings_org_time', 'meetings', ['organization_id', 'scheduled_start_time'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_meetings_project_time', 'meetings', ['project_id', 'scheduled_start_time'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_table('bot_sessions',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='QUEUED', nullable=False),
    sa.Column('worker_node', sa.String(length=120), nullable=True),
    sa.Column('join_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('raw_event_log', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED', 'JOINING', 'WAITING_FOR_ADMISSION', 'JOINED', 'RECORDING', 'ENDED', 'FAILED')", name='chk_bot_session_status'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bot_sessions_meeting', 'bot_sessions', ['meeting_id', 'created_at'], unique=False)
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('participant_type', sa.String(length=20), server_default='USER', nullable=False),
    sa.Column('attendance_status', sa.String(length=20), server_default='INVITED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("attendance_status IN ('INVITED', 'JOINED', 'ABSENT')", name='chk_attendance'),
    sa.CheckConstraint("participant_type IN ('HOST', 'USER')", name='chk_participant_type'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_user')
    )
    op.create_table('meeting_reports',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='NOT_STARTED', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('decisions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('structured_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED')", name='chk_report_status'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id')
    )
    op.create_table('action_items',
    sa.Column('meeting_report_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='NOT_STARTED', nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='chk_action_priority'),
    sa.CheckConstraint("status IN ('NOT_STARTED', 'PARTIALLY_DONE', 'DONE', 'BLOCKED')", name='chk_action_status'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_report_id'], ['meeting_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_items_meeting', 'action_items', ['meeting_id'], unique=False)
    op.create_index('idx_action_items_owner', 'action_items', ['owner_user_id', 'status'], unique=False)
    op.create_table('report_artifacts',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=20), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("artifact_type IN ('PDF', 'JSON_EXPORT')", name='chk_artifact_type'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['meeting_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifacts_lookup', 'report_artifacts', ['meeting_id', 'artifact_type'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('bot_session_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('speaker_label', sa.String(length=80), nullable=False),
    sa.Column('speaker_user_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_session_id'], ['bot_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transcript_sequence', 'transcript_segments', ['meeting_id', 'sequence_no'], unique=False)
    op.create_index('idx_transcript_time', 'transcript_segments', ['meeting_id', 'start_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transcript_time', table_name='transcript_segments')
    op.drop_index('idx_transcript_sequence', table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index('idx_artifacts_lookup', table_name='report_artifacts')
    op.drop_table('report_artifacts')
    op.drop_index('idx_action_items_owner', table_name='action_items')
    op.drop_index('idx_action_items_meeting', table_name='action_items')
    op.drop_table('action_items')
    op.drop_table('meeting_reports')
    op.drop_table('meeting_participants')
    op.drop_index('idx_bot_sessions_meeting', table_name='bot_sessions')
    op.drop_table('bot_sessions')
    op.drop_index('idx_meetings_project_time', table_name='meetings', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_meetings_org_time', table_name='meetings', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_meetings_idempotency', table_name='meetings', postgresql_where='idempotency_key IS NOT NULL')
    op.drop_table('meetings')
    op.drop_index('idx_refresh_tokens_lookup', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_projects_org_name', table_name='projects', postgresql_where='deleted_at IS NULL')
    op.drop_table('projects')
    op.drop_index('idx_audit_logs_lookup', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_users_org_role', table_name='users', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_users_email', table_name='users', postgresql_where='deleted_at IS NULL')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
